# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for TQUIC Path Manager
#

obj-$(CONFIG_TQUIC_PATH_MANAGER) += tquic_pm.o

tquic_pm-y := \
	pm_types.o \
	path_manager.o \
	pm_netlink.o \
	pm_userspace.o \
	path_validation.o \
	nat_keepalive.o
