# SPDX-License-Identifier: GPL-2.0-only
#
# TQUIC Interoperability Testing Framework Makefile
#

obj-$(CONFIG_TQUIC_INTEROP_TEST) += tquic_interop.o

tquic_interop-y := interop_framework.o rfc9000_tests.o
