# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for TQUIC Multipath Extension (RFC 9369)
#

obj-$(CONFIG_TQUIC_MULTIPATH) += tquic_multipath.o

tquic_multipath-y := \
	mp_frame.o \
	mp_ack.o \
	path_abandon.o
